/**
 * Build script: Fetches emoji data from emojilib and generates a TypeScript module
 * 
 * This script runs during build time (prebuild) to avoid runtime network requests.
 * The generated file is gitignored as it's a build artifact.
 */

import { resolve } from 'node:path'

const EMOJI_LIB_URL = 'https://unpkg.com/emojilib@^4.0.0'
const OUTPUT_PATH = resolve(import.meta.dirname, '../javascripts/emoji-data.ts')

type RawEmojiData = Record<string, string[] | string>
type ProcessedEmojiData = Record<string, string>

/**
 * Fetch raw emoji data from emojilib
 */
async function fetchRawData(): Promise<RawEmojiData> {
  const response = await fetch(EMOJI_LIB_URL)
  if (!response.ok) {
    throw new Error(`Failed to fetch emoji data: ${response.statusText}`)
  }
  return response.json() as Promise<RawEmojiData>
}

/**
 * Process raw emoji data: convert keyword arrays to space-separated strings
 */
function processEmojiData(rawData: RawEmojiData): ProcessedEmojiData {
  const processed: ProcessedEmojiData = {}

  for (const [emoji, keywords] of Object.entries(rawData)) {
    processed[emoji] = Array.isArray(keywords) ? keywords.join(' ') : keywords
  }

  return processed
}

/**
 * Generate TypeScript module content from processed data
 */
function generateTypeScriptModule(data: ProcessedEmojiData): string {
  const timestamp = new Date().toISOString()
  const jsonData = JSON.stringify(data, null, 2)

  return `/**
 * Auto-generated emoji data from emojilib
 * Generated at: ${timestamp}
 * DO NOT EDIT THIS FILE MANUALLY
 */

export const emojiData: Record<string, string> = ${jsonData} as const
`
}

/**
 * Main function: orchestrates the data fetching and file generation
 */
async function main(): Promise<void> {
  console.log('Fetching emoji data from emojilib...')

  try {
    const rawData = await fetchRawData()
    const processedData = processEmojiData(rawData)
    const moduleContent = generateTypeScriptModule(processedData)

    await Bun.write(OUTPUT_PATH, moduleContent)

    console.log(`✓ Fetched ${Object.keys(processedData).length} emojis`)
    console.log(`✓ Generated ${OUTPUT_PATH}`)
  } catch (error) {
    console.error('Error generating emoji data:', error)
    process.exit(1)
  }
}

main()
