/**
 * Build script to fetch emoji data from emojilib and generate a TypeScript file
 * This runs during build time to avoid runtime fetching
 */

const EMOJI_LIB_URL = 'https://unpkg.com/emojilib@^4.0.0'

async function fetchEmojiData() {
  console.log('Fetching emoji data from emojilib...')
  
  try {
    const response = await fetch(EMOJI_LIB_URL)
    if (!response.ok) {
      throw new Error(`Failed to fetch emoji data: ${response.statusText}`)
    }
    
    const rawEmojiData = await response.json() as Record<string, string[] | string>
    
    // Convert array of keywords to space-separated string
    const emojiData: Record<string, string> = {}
    for (const [emoji, keywords] of Object.entries(rawEmojiData)) {
      if (Array.isArray(keywords)) {
        emojiData[emoji] = keywords.join(' ')
      } else {
        emojiData[emoji] = keywords
      }
    }
    
    console.log(`✓ Fetched ${Object.keys(emojiData).length} emojis`)
    
    // Generate TypeScript file with the emoji data
    const tsContent = `/**
 * Auto-generated emoji data from emojilib
 * Generated at: ${new Date().toISOString()}
 * DO NOT EDIT THIS FILE MANUALLY
 */

export const emojiData: Record<string, string> = ${JSON.stringify(emojiData, null, 2)} as const
`
    
    // Write to file
    const outputPath = './javascripts/emoji-data.ts'
    await Bun.write(outputPath, tsContent)
    console.log(`✓ Generated ${outputPath}`)
    
  } catch (error) {
    console.error('Error fetching emoji data:', error)
    process.exit(1)
  }
}

fetchEmojiData()
